"""Render the canonical map JSON into a clean, self-contained HTML page the team
can open directly in Google Drive (no markdown viewer needed).

Run: python scripts/render_canonical_map_html.py
Emits: references/canonical_map.html
"""
from __future__ import annotations
import html
import json
import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(HERE, "zhong2025", "assets", "canonical_map.json")
OUT = os.path.join(HERE, "references", "canonical_map.html")

CSS = """
:root{--bg:#f8faf6;--card:#fff;--ink:#16201c;--soft:#54605a;--line:#d9e0d7;
--fluoro:#0f6c4f;--fluoro-bg:#e3f1ea;--heat:#963923;--heat-bg:#f6e2db;--amber:#76500f;--amber-bg:#f5ead2;--mono:ui-monospace,"SF Mono",Menlo,Consolas,monospace}
@media (prefers-color-scheme:dark){:root{--bg:#0c1210;--card:#141d18;--ink:#e7ede8;--soft:#9fb0a7;--line:#26312b;
--fluoro:#63d5a6;--fluoro-bg:#12271d;--heat:#e87a60;--heat-bg:#2a1410;--amber:#d29a45;--amber-bg:#241a0b}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,system-ui,sans-serif}
.wrap{max-width:1040px;margin:0 auto;padding:2rem 1.3rem 4rem}
h1{font-size:1.9rem;margin:.2rem 0 .3rem;letter-spacing:-.01em}
h2{font-size:1.25rem;margin:2.4rem 0 .7rem}
.sub{color:var(--soft);margin:0 0 1.4rem}
.pill{display:inline-block;font:.8rem/1 var(--mono);background:var(--fluoro-bg);color:var(--fluoro);padding:.4em .6em;border-radius:6px;margin:.15rem .3rem .15rem 0}
.warn{background:var(--heat-bg);border-left:3px solid var(--heat);padding:.7rem .9rem;border-radius:0 8px 8px 0;margin:.8rem 0;color:var(--ink)}
.note{color:var(--soft);font-size:.92rem;margin:.5rem 0 0}
table{border-collapse:collapse;width:100%;margin:.4rem 0 1rem;font-size:.92rem;background:var(--card);border:1px solid var(--line);border-radius:10px;overflow:hidden}
th,td{text-align:left;padding:.5rem .7rem;border-bottom:1px solid var(--line);vertical-align:top}
th{background:color-mix(in oklab,var(--card) 85%,var(--ink) 6%);font-weight:600;position:sticky;top:0}
tr:last-child td{border-bottom:0}
code{font-family:var(--mono);font-size:.86em;background:color-mix(in oklab,var(--card) 70%,var(--ink) 8%);padding:.05em .35em;border-radius:4px}
.tag{font:.72rem/1 var(--mono);padding:.25em .5em;border-radius:5px}
.c-sup{background:var(--fluoro-bg);color:var(--fluoro)}.c-unsup{background:var(--amber-bg);color:var(--amber)}
.c-grating{background:#e6e9ff;color:#3a41b0}.c-naive{background:color-mix(in oklab,var(--card) 60%,var(--ink) 12%);color:var(--soft)}
@media (prefers-color-scheme:dark){.c-grating{background:#1a1d33;color:#9aa2ff}}
.scroll{overflow-x:auto}
.rew{color:var(--fluoro);font-weight:600}
"""


def esc(x):
    return html.escape(str(x)) if x is not None else ""


def cohort_tag(c):
    return f'<span class="tag c-{esc(c)}">{esc(c)}</span>'


def main():
    d = json.load(open(SRC))
    meta, areas, roles, mice, recs = d["_meta"], d["brain_areas"], d["stimulus_roles"], d["mice"], d["recordings"]
    P = []
    P.append("<div class='wrap'>")
    P.append(f"<h1>Zhong et al. 2025 — canonical map</h1>")
    P.append(f"<p class='sub'>Deterministic, auto-generated single source of truth · "
             f"<b>{meta['counts']['recordings']} recordings · {meta['counts']['mice']} mice</b>. "
             f"Generated by <code>scripts/build_canonical_map.py</code> — do not hand-edit.</p>")
    P.append(f"<div class='warn'>⚠️ Cohorts <b>overlap</b>: a <code>naive</code> recording reuses a "
             f"supervised/unsupervised/grating mouse. See the <b>also</b> column. Never treat one mouse "
             f"(e.g. VR2, TX105) as “the” supervised/unsupervised mouse — they are examples among many.</div>")

    P.append("<h2>Cohorts</h2><div class='scroll'><table><tr><th>code</th><th>meaning</th></tr>")
    for k, v in d["cohorts"].items():
        P.append(f"<tr><td>{cohort_tag(k)}</td><td>{esc(v)}</td></tr>")
    P.append("</table></div>")

    P.append("<h2>Brain-area codes <span class='note'>(iarea → region · authoritative)</span></h2><div class='scroll'><table>")
    P.append("<tr><th>group</th><th>iarea codes</th><th>region</th><th>role</th></tr>")
    for k, v in areas.items():
        P.append(f"<tr><td><code>{esc(k)}</code></td><td><code>{esc(v['iarea'])}</code></td>"
                 f"<td>{esc(v['region'])}</td><td>{esc(v['role'])}</td></tr>")
    P.append("</table></div>")
    P.append("<div class='warn'>The early team map <code>{1:'V1',2:'mHV',3:'aHV'}</code> is <b>incorrect</b> — "
             "V1 is code <b>8</b>, not 1. Use the table above.</div>")

    P.append("<h2>Stimulus roles <span class='note'>(stim_id → meaning · functional, per session)</span></h2><div class='scroll'><table>")
    P.append("<tr><th>stim_id</th><th>role</th><th>meaning</th><th>rewarded</th></tr>")
    for k in sorted(roles, key=int):
        v = roles[k]
        rew = "<span class='rew'>✅ reward</span>" if v["rewarded"] else "—"
        P.append(f"<tr><td>{esc(k)}</td><td><code>{esc(v['name'])}</code></td><td>{esc(v['meaning'])}</td><td>{rew}</td></tr>")
    P.append("</table></div>")
    P.append(f"<p class='note'>Selectivity <b>d′ compares <code>leaf1</code> (2) vs <code>circle1</code> (0)</b>. "
             "Roles come from which wall is rewarded (<code>get_cat_id</code>), not the physical texture.</p>")

    P.append(f"<h2>Mice ({len(mice)})</h2><div class='scroll'><table>")
    P.append("<tr><th>mouse</th><th>cohort</th><th>also</th><th>sex</th><th>recordings</th></tr>")
    for k in sorted(mice):
        m = mice[k]
        also = " ".join(cohort_tag(c) for c in m["also"]) or "—"
        P.append(f"<tr><td><code>{esc(m['mouse'])}</code></td><td>{cohort_tag(m['primary_cohort'])}</td>"
                 f"<td>{also}</td><td>{esc(m['gender'] or '?')}</td><td>{esc(m['n_recordings'])}</td></tr>")
    P.append("</table></div>")

    order = {"sup": 0, "unsup": 1, "grating": 2, "naive": 3}
    P.append(f"<h2>Recordings ({len(recs)}) <span class='note'>· grouped by cohort → stage. "
             "Full per-recording detail in <code>canonical_map.json</code>.</span></h2>")
    from collections import defaultdict
    grouped = defaultdict(lambda: defaultdict(list))
    for rid, r in recs.items():
        grouped[r["cohort"]][r["stage"]].append((r["mouse"], r["date"], rid))
    for coh in sorted(grouped, key=lambda c: order.get(c, 9)):
        P.append(f"<p style='margin:.9rem 0 .2rem'>{cohort_tag(coh)}</p><div class='scroll'><table>")
        P.append("<tr><th>stage</th><th>mice (date)</th></tr>")
        for stage in sorted(grouped[coh]):
            items = sorted(grouped[coh][stage])
            cells = ", ".join(f"<code>{esc(m)}</code> ({esc(dt)})" for m, dt, _ in items)
            P.append(f"<tr><td>{esc(stage) or '—'}</td><td>{cells}</td></tr>")
        P.append("</table></div>")
    P.append("</div>")

    doc = (f"<!doctype html><html lang='en'><head><meta charset='utf-8'>"
           f"<meta name='viewport' content='width=device-width,initial-scale=1'>"
           f"<title>Zhong 2025 — canonical map</title><style>{CSS}</style></head><body>"
           + "".join(P) + "</body></html>")
    open(OUT, "w").write(doc)
    print(f"WROTE {OUT} ({len(doc):,} bytes)")


if __name__ == "__main__":
    main()
